apiVersion: v2
name: pagerduty-exporter
type: application
description: A Helm chart for pagerduty-exporter
home: https://github.com/webdevops/pagerduty-exporter
version: 1.0.2
appVersion: 22.9.1
keywords:
- pagerduty-exporter
maintainers:
- email: mblaschke82@gmail.com
  name: mblaschke
sources:
- https://github.com/webdevops/pagerduty-exporter/
