config:
  queries:
    azurerm_subscription_info:
      metric: azurerm_subscription_info
      query: |-
        ResourceContainers
        | where type == "microsoft.resources/subscriptions"
      value: 1
      fields:
        - name: name
        - name: subscriptionId
          target: subscriptionID
          type: id
      defaultField:
        type: ignore

secrets:
  test: "{{ $.Release.Namespace }}"

secretsEnableTemplateFunctions: true

extraVolumeMounts:
  - mountPath: /var/run/secrets/tokens
    name: vault-token
extraVolumes:
  - name: vault-token
    projected:
      sources:
        - serviceAccountToken:
            path: vault-token
            expirationSeconds: 7200
            audience: vault
