{{- if .Values.netpol.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "azure-scheduledevents-manager.fullname" . }}
  namespace: {{ template "azure-scheduledevents-manager.namespace" . }}
  labels: {{ include "azure-scheduledevents-manager.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "azure-scheduledevents-manager.selectorLabels" . | nindent 6 }}
  policyTypes: {{ toYaml .Values.netpol.policyTypes | nindent 4 }}
  ingress: {{ toYaml .Values.netpol.ingress | nindent 4 }}
  egress: {{ toYaml .Values.netpol.egress | nindent 4 }}
{{- end }}
