{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "azure-scheduledevents-manager.fullname" . }}
  labels: {{ include "azure-scheduledevents-manager.labels" . | indent 4 }}
rules:
# Allow kured to read spec.unschedulable
# Allow kubectl to drain/uncordon
#
# NB: These permissions are tightly coupled to the bundled version of kubectl; the ones below
# match https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/kubectl/cmd/drain.go
#
- apiGroups: [""]
  resources: ["nodes"]
  verbs:     ["watch", "list", "get", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs:     ["watch", "list", "delete", "get"]
# Allow to get a list of PODs
- apiGroups: ["extensions", "apps"]
  resources: ["daemonsets"]
  verbs:     ["get"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs:     ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "azure-scheduledevents-manager.fullname" . }}
  labels: {{ include "azure-scheduledevents-manager.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "azure-scheduledevents-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | quote }}
  namespace: {{ include "azure-scheduledevents-manager.namespace" . | quote }}
{{- end }}
