---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "azure-janitor.fullname" . }}
  namespace: {{ template "azure-janitor.namespace" . }}
  labels: {{ include "azure-janitor.labels" . | indent 4 }}
data:
{{- range $index, $val := .Values.secrets }}
  {{ $index | quote }}: {{ $val | b64enc | quote }}
{{- end }}
