---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "kube-pool-manager.fullname" . }}
  namespace: {{ template "kube-pool-manager.namespace" . }}
  labels: {{ include "kube-pool-manager.labels" . | indent 4 }}
data:
  config.yaml: |-
{{ .Values.config | indent 4 }}
