{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kube-pool-manager.fullname" . }}
  namespace: {{ template "kube-pool-manager.namespace" . }}
  labels: {{ include "kube-pool-manager.labels" . | indent 4 }}
data:
{{- range $index, $val := .Values.secrets }}
  {{- if $.Values.secretsEnableTemplateFunctions }}
  {{ $index | quote }}: {{ tpl ($val | toString) $ | b64enc | quote }}
  {{- else }}
  {{ $index | quote }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
